// Generated by CoffeeScript 1.6.3
(function() {
  var $;

  $ = jQuery;

  $(document).ready(function() {
    if ($(".tabs").length) {
      $(".tabs-header").find("a").on('click', function(event) {
        var idx, that;
        event.preventDefault();
        that = $(this);
        if (!(that.hasClass('active'))) {
          idx = that.index() - 1;
          $(".tabs-header").find("a").removeClass("active");
          that.addClass("active");
          return $(".tabs-content").find(".tab").hide().eq(idx).show();
        }
      });
    }
  });

  jQuery(window).load(function() {
    if ($(".tabs").length) {
      $(".tabs-header").find("a").first().click();
    }
  });

}).call(this);
