// Generated by CoffeeScript 1.6.3
(function() {
  var $, cartLogic, initCarusel, initSlider, initTabs;

  $ = jQuery;

  $(document).ready(function() {
    if ($('#slides').length) {
      initSlider();
    }
    if ($('#mycarousel').length) {
      initCarusel();
    }
    if ($('.tab-section').length) {
      initTabs();
      $('.tab-nav').find('a').first().click();
    }
    $(".triger-brand").on('click', function() {
      return $(this).parents('.brand-parts').toggleClass('closed');
    });
    if ($('.cart').length) {
      cartLogic();
    }
  });

  jQuery(window).load(function() {});

  initSlider = function() {
    return $('#slides').slidesjs({
      width: 940,
      height: 324,
      play: {
        active: false,
        effect: "slide",
        interval: 40000,
        auto: true,
        swap: true,
        pauseOnHover: false,
        restartDelay: 2500
      },
      navigation: true
    });
  };

  initCarusel = function() {
    return $('#mycarousel').jcarousel({
      scroll: 1,
      visible: 3,
      wrap: 'circular'
    });
  };

  initTabs = function() {
    return $(".tab-nav").find('a').on('click', function(event) {
      var id;
      event.preventDefault();
      if (!($(this).hasClass('active'))) {
        id = $(this).attr('href');
        $(".tab-nav").find('.active').removeClass('active');
        $(this).addClass('active');
        $(".tab").hide();
        return $(id).show();
      }
    });
  };

  cartLogic = function() {
    $('.cart-title').on('click', function() {
      if ($(this).hasClass('opened')) {
        $(this).removeClass('opened');
        return $('.cart-content').fadeOut();
      } else {
        $(this).addClass('opened');
        return $('.cart-content').fadeIn();
      }
    });
    $(".cart").find('.icons-delete-button').on('click', function() {
      $(this).parents('.cart-content').fadeOut();
      return $('.cart-title').removeClass('opened');
    });
    $('.item-delete').find('.icons-close-small').on('click', function(e) {
      e.stopPropagation();
      return $(this).parents('.item-holder').remove();
    });
    return $("body").on('click', function(e) {
      if (!($(e.target).closest('.cart-content').length) && !($(e.target).closest('.cart-title').length)) {
        $('.cart-title').removeClass('opened');
        return $(".cart-content").fadeOut();
      }
    });
  };

}).call(this);
