// Generated by CoffeeScript 1.6.3
(function() {
  var $;

  $ = jQuery;

  $(document).ready(function() {
    if ($('#slides').length) {
      $('#slides').slidesjs({
        width: 940,
        height: 528,
        play: {
          active: false,
          effect: "slide",
          interval: 4000,
          auto: true,
          swap: true,
          pauseOnHover: false,
          restartDelay: 2500
        },
        navigation: true
      });
    }
    if ($('#mycarousel').length) {
      $('#mycarousel').jcarousel({
        scroll: 1,
        visible: 3,
        wrap: 'circular'
      });
    }
  });

  jQuery(window).load(function() {});

}).call(this);
